# Generated by Django 3.0.1 on 2023-11-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
