# Generated by Django 3.0.1 on 2023-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_concert_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
