# Generated by Django 3.0.1 on 2023-12-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biog', models.TextField()),
            ],
        ),
    ]
