# Generated by Django 3.0.1 on 2023-12-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
