# Generated by Django 3.2 on 2023-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
