# Generated by Django 3.2.23 on 2023-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music', '0002_rename_composerfirstname_sheetmusic_composer_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='arranger',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
