# Generated by Django 3.2.23 on 2023-11-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music', '0003_auto_20231110_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='sheetmusic',
            old_name='title',
            new_name='name',
        ),
    ]
